project:
  title: "POL837 Research Paper"
  render:
    - paper-text/sections/1_introduction.qmd
    - paper-text/sections/3_empirical_strategy.qmd
    - paper-text/main.qmd

title: "POL837 Research Paper"

format: 
     pdf:
        fontsize: 12pt
        pdf-engine: xelatex
        mathfont: "Libertinus Math"
        latex-output-dir: output

bibliography: paper-text/references.bib
csl: paper-text/apa7_normal.csl