---
# Introduction
suppress-bibliography: true
---

# Introduction

Whether voters can truly capture a realistic appraisal of the state of the world at the polls remains a core research topic in the study of politics. In an ideal scenario, individuals will be able to adequately judge the strengths and weaknesses of politicians punishing poor performers and providing incentives for new leaders to perform competently while in office. This well known argument of *voter rationality* by @responsibleElectorate builds the foundation of retrospective voting, which models citizens as rational observers of government past-performance [@ferejohnIncumbentperformanceelectoral1986; @healyRetrospectivevotingreconsidered2013]. An adequate system of retrospective voting has can to efficient political outcomes, where politicians who underperform leave office resulting in greater democratic accountability [@besleyPrincipledagentspolitical2006; @perssonPoliticaleconomicsexplaining2002]. 

However, modern researchers have challenged the view that voters can adequately appraise the performance of a politician, finding a variety of biases in the way voters attribute responsibility to political leaders, which challenges the foundational basis of the perfect retrospective voter [@healyRetrospectivevotingreconsidered2013]. In this paper, I contribute to this stream of the literature by focusing on how seemingly irrelevant events can significantly affect presidential approval. I do this by leveraging an ordinary yet impactful natural experiment: transient temperature variations across municipalities in a developing democracy. 

I construct a novel dataset by merging the AmericasBarometer (AB) public opinion survey data with CPC Global Unified temperature data in Ecuador. Given that daily temperature changes can be assumed to be random, I exploit this variation to estimate the impact of temperature on presidential approval ratings. The core result of the paper is that higher temperatures have a negative and statistically significant relationship with presidential approval, which suggests that voters commit attribution errors when evaluating politicians. I ascribe this result to a mood misattribution caused by heat discomfort, a robust result across other disciplines but relatively unexplored in the study of political behaviour. 

Most of the retrospective voting literature has focused on economic voting, which focuses examining the empirical relationship between economic indicators and political attitudes [@ducheconomicvotehow2008; @kiewietretrospectiveretrospectivevoting1984; @berlemanneconomicdeterminantspresidential2014]. This literature has found mixed results, but one core finding is that in Latin America, economic variables cannot have little explanatory power on presidential approval [@laytonChapterCitizensecurity2016]. Further, other researchers have found evidence of cognitive and emotional biases in the evaluation of politician performance by voters [@hartQualitycontrolexperiments2023; @kahnemanstudystatisticalintuitions1982; @beckDoesthereexist1982; @tilleygovernmentblameexperimental2011], yet few have studied the impact of random events such as the I study in this paper [@healyIrrelevanteventsaffect2010; @healyRandomeventseconomic2010; @christopherhachenauthorDemocracyrealistswhy2016].

<!-- which has long discussed if voters truly evaluate politicians based on the management of the economy, or the economy is seen through partisan lens. Presidential approval is closely related to this, considering the ample perception of the executive as the main responsible for the economy. Attribution errors have been found in this environment, where voters cannot accurately judge the performance due to a lack of information of politicians' mandates [@healyMyopicvotersnatural2009]. -->

<!-- While the most obvious mistake of voters could be seen as the lack of information, cognitive biases can also lead to the incorrect attribution of responsibility to political leaders. Cognitive biases such as an increased emphasis in the election year, party cues, heuristics, have been found to be present in experimental settings [@hartQualitycontrolexperiments2023]. Further, there is evidence that voters can commit severe attribution errors by assigning blame to politicians because of irrelevant events [@healyIrrelevanteventsaffect2010; @achenBlindretrospectionelectoral2017, @healyRandomeventseconomic2010]. The existence of these biases has been confirmed in recent observational studies, which find that in Latin America economic variables have little explanatory power in explaining presidential approval [@berlemanneconomicdeterminantspresidential2014; @laytonChapterCitizensecurity2016]. -->

<!-- Nevertheless, even though research has shown clear results on the existence of biases and a growing importance on attribution errors, the literature is still limited in the exploration of unrelated factors that can affect presidential approval, such as the weather. This is important in developing democracies, where weather can be a more relevant factor in the lives of citizens, and where the literature on retrospective voting is still limited. -->

<!-- Outside political science, it has been found that weather is a strong determinant of mood and personal evaluations of happiness and satisfaction [@barrington-leighimpactdailyweather2017; @barrington-leighWeathertransientinfluence2008; @lucasDoeslifeseem2013]. Further, organizational behaviour literature has also determined that weather can impact the way that subjective performance evaluations are made [@dellereffectweathersubjective2022], which can be seen as a parallel to the way that voters evaluate politicians. Given that the literature on retrospective voting is based on the idea that mood can impact the way that voters evaluate politicians [@bowerMoodmemory1981; @schwarzMoodmisattributionjudgments1983], it is reasonable to assume that weather can have an impact on presidential approval, but to my knowledge, this is the only paper that explores this relationship. -->
The paper proceeds as follows. In the next section, I present the empirical approach of the paper, which includes the data. In the Results section, I present the paper's main findings. I also present the heterogenous effects of temperature on presidential approval. In the conclusion, I discuss the main findings of the paper and their implications for the literature on retrospective voting and attribution errors.
