---
# Theory
suppress-bibliography: true
---

# Retrospective voting and weather

In this section, I review the theory which informs my empirical approach. I analyze relevant literature on retrospective voting, which has mostly centered on economic voting, as well as the literature on presidential approval. I then provide an overview of my causal argument based on psychology theory on mood. Further, I review existing results on the impact of weather on mood and decision-making. 

Economic voting research has long discussed if the economy truly explains voting behaviour (i.e. voters will punish politicians for poor management of the economy), or if the economy is seen through a partisan lens, implying that the management of the economy itself is irrelevant [@wlezien_etal97;@lewis-beck06; @lewis-beck_etal08]. Difficult identification challenges emerge from this type of performance models due to the endogeneity of the public's perceptions of the economy and vote choice [@anderson07;@kiewiet_rivers84]. This endogeneity presents itself in even the most basic analyses: one cannot identify causality from correlations of Republican vote share and economic growth, since Republican president's may be more likely to be elected in times of economic growth. 

Most retrospective voting research in Latin America has focused on economic voting too, as well as on populism and the recent rise of leftist parties and populism [@benton05; @lee14; @wiesehomeier_doyle13;@murillo_etal10]. The literature finds no clear conclusions. However, @veiga13 finds that usual macroeconomic variables are not reliable predictors of vote choice on Latin American countries. Regarding leftist parties and populism, evidence has shown that the early 2000's *pink tide* in Latin America may have been a result of retrospective voting and discontent with establishment parties [@wiesehomeier_doyle13].

The literature on presidential approval is adjacent to economic voting, since it has mostly focused on estimating *popularity functions* to determine the relationship between presidential popularity and other variables [@berlemann_enkelmann14a]. Macroeconomic variables such as inflation and unemployment have been found to significantly affect presidential approval in some cases, however, no definitive results have been found. Results are highly dependent on context, and on the researcher's choice of variables, model specification, frequency, time frame, among others. donovan_etal20 show that presidential approval is also impacted by the public's partisan identity. Recent findings show that perceptions of corruption can act as significant predictors of presidential approval [@jung_oh20], especially in Latin America, where other work has shown a reduced importance of standard economic variables [@cerda_vergara23]. 

The debate that retrospective voting has given rise to has incentivized the use of advanced causal inference and experimental techniques to overcome identification challenges. This renewed approach has allowed for a more precise understanding of the mechanisms behind retrospective voting. Some of the recent work involves the mistakes that voters make when evaluating politicians' performance, going beyond the lack of knowledge about economic information. Rather, recent research has found that citizens tend to commit errors consistent with decision-making beyond political life. 

Events that should be irrelevant to the vote choice are one type of such biases. Though disputed, @achen_bartels17 famously presented evidence of shark attacks impacting Woodrow Wilson's vote share in 1916. Further, @healy_etal10 find that football games can positively impact the vote share of incumbents, results also consistent with irrelevant events impacting voting behaviour. Events that politicians have no control upon can impact their electoral outcomes if voters are assumed to be affected by mood in their performance judgments, a well-documented phenomenon in other fields. In an experimental setting, @schwarz_clore83 show how inducing positive moods led subjects to report more feelings of satisfaction relative to subjects which were induced negative moods. Most importantly, it was shown that *people in bad moods were more likely to search for information to explain their mood* relative to those in a happy mood. This is direct evidence for attribution errors: if an outside circumstance induces a negative mood, people may be more likely to attribute their mood to search for information that confirms their mood, rather than the other way around. Additionally, @bower81 show that people who were induced a mood were more likely to recall information that was congruent with their mood. This can confirm misattribution errors in voters, who may be more likely to recall negative information about politicians if they are in a bad mood, and vice versa.

Fields other than political science have studied weather extensively, mostly showing significant impacts across a range of variables. Notably, @keller_etal05 find that pleasant weather (higher temperature or barometric pressure) has a positive impact on mood for U.S. subjects. @kampfer_mutz13 and @schmiedeberg_schroder14 find conflicting results of the impact of sunnier days on life satisfaction using survey data from Germany. @lucas_lawless13, do not find reliable evidence of weather impacting life satisfaction using U.S. survey data. In Canada, @barrington-leigh08 finds a positive effect of sunnier days on trust in neighbours using Canadian survey data. Further, @barrington-leigh_behzadnejad17, find that temporary rainfall variations have a significant, yet small negative impact in life satisfaction, especially for individuals with poor health and women. @lignier_etal23 find that higher temperatures in prolonged dry temperatures have a negative impact on life satisfaction in Australia. Beyond life satisfaction, @deller_michels22 show that cloudy days have a significant impact on the way that managers evaluate subordinates across field experiments in the United States. Additionally, @quijano-ruiz23, using the same CPC daily weather data for Ecuador, finds an effect of daily temperature changes on self-rated health for female survey respondents only.

The causal mechanism that the article's empirical approach leverages draws from @schwarz_clore83 and @bower81. Weather impacts mood, which then causes citizens to attribute their moods to external circumstances. If citizens consider higher temperatures to be "bad weather", their mood can be negatively impacted, making them more likely to negatively evaluate the president as a result of their discomfort. The effect is particularly salient for the president given the importance attributed to the executive for the management of domestic affairs. According to the theory, voters will attribute their mood to a external situation (the question being asked by the interviewer, which in this case relates to the president) and may even justify it by searching for negative events that confirm their mood, as proposed by @bower81.

In summary, retrospective voting literature has had an economic focus, which underscores the importance of controlling for economic perceptions in any formal empirical model of political behaviour. The Latin American context has shown some degree of resemblance to developed countries, but also some differences, notably in how certain ideological factors may moderate political behaviour to larger extent than developed countries. Presidential approval rating is extensive and has provided many recommendations for the estimation of popularity functions, notably, incorporating data at many frequencies and aggregations. However, this may not be possible or applicable in all contexts due to data availability. My theory on the impact of weather on presidential approval is supported by a growing literature on the impact of weather on mood and life satisfaction, which has shown mostly significant impacts of "better" weather across several variables. The causal mechanism I draw from is supported by psychological theory, which has shown that mood can impact the way that individuals process information, and how they attribute their mood to external circumstances.

I thus hypothesize that because Ecuador is a tropical country, citizens may be more likely to attribute their discomfort to the president on hotter days, which will lead to a decrease in presidential approval. The effect of a higher daily temperature on presidential approval is then expected to be negative. 