---
# Conclusion
suppress-bibliography: true
---

# Conclusion

This paper has shown that daily temperature has a significant negative effect on presidential approval in Ecuador. Survey respondents are about 1.9 to 2.2 percentage points less likely to approve of the president when maximum daily temperatures increase by one degree. This result is robust to the inclusion of socioeconomic and political behaviour controls, including variables which control for partisanship, trust in the police, democracy, personal ideology identification, evaluations of the economy, among others. 
These results are consistent with some literature on retrospective voting and voter errors, which suggests that voters may commit attribution errors when evaluating politician's performance. I validate findings from @barrington-leighimpactdailyweather2017,  @lignierDoesclimateimpact2023 and @quijano-ruizAssessingreliabilityselfrated2023, who find that weather impacts behaviour. 

I argue that the weather affects the mood of individuals negatively, and in turn individuals search externally for factors to validate their mood. This leads to a misattribution of mood to the president's performance, which results in lower approval ratings. The causal mechanism which explains these empirical findings rests on psychological theories of mood misattribution. These describe that individuals in a bad mood are more likely to report feelings of life dissatisfaction, and that they are more likely to attribute their mood to external factors [@schwarzMoodmisattributionjudgments1983;@bowerMoodmemory1981]. I argue that warmer weather in Ecuador may lead to a negative moods, which in turn makes citizens direct their emotions towards the president's performance. This is consistent with the literature on the impact of weather across a range of outcomes, which finds that weather can have a significant impact on behaviour [@kellerwarmheartclear2005; @barrington-leighimpactdailyweather2017;@lignierDoesclimateimpact2023; @quijano-ruizAssessingreliabilityselfrated2023; @dellereffectweathersubjective2022].

The results also show that the effect of temperature on presidential approval is not constant across the population. Women are more sensitive to higher temperatures than men, also found by @quijano-ruizAssessingreliabilityselfrated2023 using CPC weather data in Ecuador and by @barrington-leighimpactdailyweather2017 in Canada. I find that the effect of temperature on presidential approval is conditional on the region of the country and the political ideology of the survey respondent. The result of heterogeneity across ideological groups produces conflicting results, suggesting that minimum and maximum temperatures have different effects on survey respondents identifying closer to the political right. I find no difference of the effect of temperature between those that negatively evaluate the economy compared to those who evaluate it positively or equal relative to last year. Results for regional heterogeneity, while understandable given that the Amazon region is the most humid and warm region in the country, are preliminary and should be taken with caution, because of the small sample size of the Amazon region in the AmericasBarometer surveys.

In the same line as @quijano-ruizAssessingreliabilityselfrated2023, who pioneers the use of CPC weather data in health services research, I introduce the use of this data for political behaviour studies, with promising results. CPC temperature data, though of lesser quality than weather station data, is of invaluable use for countries where weather station data is not available. There is a possibility that my temperature variables are subject to measurement error, which could bias my results. If this is the case, then my results are likely to be downward biased, which would suggest that the true effect of temperature on presidential approval is larger than what I estimate in this paper. The fact that I am able to find statistically significant results in an observational setting suggests that the true effect of temperature on presidential approval is likely to be larger, and future research should aim to address this possibility by using more precise temperature data, and by using more sophisticated methods to address measurement error. Replicating this study in other countries where temperature data of higher quality is available would also be valuable, in order to validate these results and understand the precision of CPC weather data for political science research.

I model the effect of temperature on presidential approval in a linear manner, which may be innacurate, given the complex nature of weather and the behavioural responses that weather may cause. Weather likely has a nonlinear effect on mood, which should be modeled with more sophisticated methods in future research to more accurately understand the effect of weather on presidential approval. I am also limited in the way that the AmericasBarometer is collected, which is bienally, and does not allow me to observe the effect of temperature on presidential approval in more granular frequencies and lower levels of spatial aggregation such as parishes or neighbourhoods.

Understanding how temperature and other weather-related variables affect political behaviour is important for extending the literature on attribution errors and retrospective voting, but even more so for understanding the way that political behaviour works in Latin America, a region which has been severely understudied in the literature. This paper is a first step in understanding the effect of weather on political behaviour in the literature, which moves away from the focus on standard variables which have been proven to be influenced by factors not present in developed countries. Understanding these mechanisms is important for better research, but also to enact public policy for democratic accountability. 
